[project]
name = "04-analytics-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kohmin", email = "61226634+kohmin@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dbt-duckdb>=1.11.0",
]

[project.scripts]
04-analytics-engineering = "04_analytics_engineering:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
